# SPDX-License-Identifier: GPL-3.0-only
"""``main_frame``: the console (1a), wired to its live DataSource.

xrc-windows.md section A's code-side footnote lists six things
``main.xrc`` cannot express: the crossings feed's DataView columns
and per-row attributes, the card imagelist, the three ``wxInfoBar``
shells, the ``main_splitter`` sash restore, per-state menu enabling,
and ``SetAppearance``. This module covers the first four for
``main_frame`` -- per-state menu enabling is ``commands.py``'s route
table (E1.4) and ``SetAppearance`` is ``theme.py``'s job (wired by
the app bootstrap, Phase 8); neither lives here. WS-D/WS-H extend
the same code-side list with the header gauges (two ``RaceClock``
dials and the ``StopLight``, built into main.xrc's placeholder
panels because XRC cannot author a ``wx.Control`` subclass), the
GO/STOP glyphs on the converted bitmap start/stop buttons, and the
review notebook's columns, rows and open-rider seam
(``flagged_list``/``console_riders_list``).

:class:`MainFrame` decorates an already-XRC-loaded ``wx.Frame`` -- it
never calls ``LoadFrame`` itself. Loading stays the caller's job
(``harness.load_window`` in tests, the app bootstrap in production),
matching every other window in this codebase and the rule this
repo's own harness states: reuse the one loader, never build a
second.

**Why no separate ``console_panel.py`` (SIMPLECODE Rule 7 -- one
module until a split earns its keep):** module-skeletons.md names
one for "feed, entry field, counters", but ``main.xrc`` never splits
those controls into their own XRC panel resource -- they are plain
children of this one frame, alongside the InfoBars, splitter and
statusbar this module already owns. Two Python files sharing one XRC
window and one set of ``FindWindowByName`` calls would be a
same-window split with no separable XRC boundary behind it, the
paper-cut kind Rule 7 warns against. If a second real window ever
needs the feed-rendering logic, extract it then.
"""

from typing import TYPE_CHECKING, Any

import wx
import wx.dataview

from rivercrossing.ride import RideStatus
from rivercrossing.ui import feed_model, ids, sound
from rivercrossing.ui.presenters.console import stop_light_mode
from rivercrossing.ui.views._support import default_card_images, find_control
from rivercrossing.ui.views.gauges import RaceClock, StopLight, go_bundle, stop_bundle

if TYPE_CHECKING:
    from collections.abc import Callable, Sequence

    from rivercrossing.ui.cards_imagelist import CardImageList
    from rivercrossing.ui.presenters.console import ConsolePresenter, Cue
    from rivercrossing.ui.presenters.data_source import (
        Counters,
        DataSource,
        FeedRow,
        RiderRow,
    )

__all__ = [
    "CONSOLE_RIDERS_LIST",
    "ELAPSED_CLOCK",
    "ELAPSED_CLOCK_PANEL",
    "FINISHED_INFOBAR",
    "FLAG_COLUMN_LABELS",
    "FLAG_COL_LAP",
    "FLAG_COL_LAP_TIME",
    "FLAG_COL_PLATE",
    "MIN_SIZE",
    "REMAINING_CLOCK",
    "REMAINING_CLOCK_PANEL",
    "REOPENED_INFOBAR",
    "REQUIRED_CONTROLS",
    "REQUIRED_CONTROL_CLASSES",
    "RESUME_INFOBAR",
    "REVIEW_NOTEBOOK",
    "RIDERS_COLUMN_LABELS",
    "RIDERS_COL_NAME",
    "RIDERS_COL_PLATE",
    "RIDERS_COL_TEAM",
    "RIDE_STATUS_LIGHT",
    "RIDE_STATUS_PANEL",
    "CrossingsFeedModel",
    "FlaggedListModel",
    "MainFrame",
    "RidersListModel",
]

_TEXT_ACCESSORS: tuple[Callable[[FeedRow], str], ...] = (
    lambda row: row.time,
    lambda row: row.plate,
    lambda row: row.entry,
    lambda row: str(row.lap),
    lambda row: row.lap_time,
    lambda row: row.total,
)

# ui/ids.py is generated from the .xrc files (R-05); these three
# names never appear there since XRC cannot author a wxInfoBar at
# all (xrc-windows.md's own code-side footnote, main.xrc's header).
RESUME_INFOBAR = "resume_infobar"
REOPENED_INFOBAR = "reopened_infobar"
FINISHED_INFOBAR = "finished_infobar"

# The WS-D gauges' frozen names, applied with SetName() because XRC
# cannot author a wx.Control subclass either -- the InfoBar rule
# above extended to RaceClock and StopLight (main.xrc's header).
ELAPSED_CLOCK = "elapsed_clock"
REMAINING_CLOCK = "remaining_clock"
RIDE_STATUS_LIGHT = "ride_status_light"

# The five WS-D/WS-H names below ARE XRC-authored (main.xrc), so the
# canonical values live in ui/ids.py (generated by tools/gen_ids.py);
# the module names stay as aliases for the call sites that read them
# as this view's own constants (e.g. REQUIRED_CONTROLS below).
ELAPSED_CLOCK_PANEL = ids.ELAPSED_CLOCK_PANEL
REMAINING_CLOCK_PANEL = ids.REMAINING_CLOCK_PANEL
RIDE_STATUS_PANEL = ids.RIDE_STATUS_PANEL
REVIEW_NOTEBOOK = ids.REVIEW_NOTEBOOK
CONSOLE_RIDERS_LIST = ids.CONSOLE_RIDERS_LIST

# console_riders_list's columns (WS-H), the same Plate | Name | Team
# shape rider_editor's own riders_list draws (xrc-windows.md C).
RIDERS_COL_PLATE = 0
RIDERS_COL_NAME = 1
RIDERS_COL_TEAM = 2
RIDERS_COLUMN_LABELS: tuple[str, ...] = ("Plate", "Name", "Team")

# flagged_list's columns (WS-H): the three cells of the canvas's
# flagged-row line ("45 · lap 6 · 07:12") as sortable columns.
FLAG_COL_PLATE = 0
FLAG_COL_LAP = 1
FLAG_COL_LAP_TIME = 2
FLAG_COLUMN_LABELS: tuple[str, ...] = ("Plate", "Lap", "Lap time")

# rider_editor.SOLO_TEAM_TEXT's dash for a solo rider's Team cell.
_TEAM_CELL = "—"

# The REOPENED corrections banner (spec §3, R-36): the clock stays
# closed and live plate entry stays off; the operator edits, voids or
# adds crossings, then finishes again. Shown by set_state on REOPENED.
REOPENED_BANNER = (
    "This ride is open for corrections — entry is locked. "
    "Edit, void, or add crossings, then finish again."
)

# xrc-windows.md section A: "Min frame 1100x700, fits 1366x768."
# XRC has no window-level minsize property (main.xrc's own header) --
# only <size>, which sets the *initial* size, not the floor.
MIN_SIZE = (1100, 700)

# How often wire_console's timer drives presenter.tick() (E4.4.1).
# 1 s keeps the clock, counters and R-35's 10 s arm auto-clear honest
# without hammering the DataView with rebuilds.
_TICK_MS = 1000


class CrossingsFeedModel(wx.dataview.DataViewIndexListModel):  # type: ignore[misc]
    """Read-only model over ``FeedRow`` rows for ``crossings_list``.

    ``# type: ignore[misc]``: wx ships no stubs (pyproject.toml's
    ``ignore_missing_imports`` for ``wx.*``), so every wx member --
    ``DataViewIndexListModel`` included -- resolves to ``Any``, and
    mypy refuses to subclass ``Any``. Unavoidable for the first wx
    base class this codebase subclasses; nothing to fix here.

    The wx-facing half of the crossings feed; ``ui/feed_model.py``
    holds the column layout and the two decisions this class
    delegates to (``card_asset_key_or_none``, the flagged-row
    lookup), so those stay testable without ``wx``
    (``tests/unit/ui/test_feed_model.py``). This class has exactly
    one consumer, :class:`MainFrame`, which is why it lives here
    rather than in its own file (SIMPLECODE Rule 7).

    Rows are supplied once at construction -- :class:`MainFrame`
    builds a fresh model each time ``show_feed`` runs rather than
    mutating this one in place, which keeps the 30-row cap (R-32)
    trivial and avoids ``DataViewIndexListModel``'s row-count-change
    notifications entirely.
    """

    def __init__(self, rows: Sequence[FeedRow], card_images: CardImageList) -> None:
        """Wrap *rows*, newest first; render cards via *card_images*."""
        super().__init__(len(rows))
        self._rows = tuple(rows)
        self._card_images = card_images
        self._flagged = feed_model.flagged_row_indexes(self._rows)
        self._edited = feed_model.edited_row_indexes(self._rows)

    def GetColumnCount(self) -> int:
        """Return the feed's fixed seven columns."""
        return len(feed_model.COLUMN_LABELS)

    def GetColumnType(self, col: int) -> str:
        """Return each column's wx variant type.

        ``"wxBitmap"`` for the card column -- see :class:`MainFrame`'s
        ``_build_columns`` for why not the newer ``"wxBitmapBundle"``.
        """
        return "wxBitmap" if col == feed_model.COL_CARD else "string"

    def GetValueByRow(self, row: int, col: int) -> Any:  # noqa: ANN401 -- wx ships no stubs
        """Return the cell value at *row*/*col*."""
        feed_row = self._rows[row]
        if col == feed_model.COL_CARD:
            return self._card_bitmap(feed_row.card)
        return _TEXT_ACCESSORS[col](feed_row)

    def GetAttrByRow(self, row: int, col: int, attr: Any) -> bool:  # noqa: ANN401, ARG002
        """Bold the whole row when its crossing is flagged or edited.

        The two bold channels share one render: a flagged crossing
        (R-34, held/short-lap) and an edited crossing (E7.2.2, one a
        correction touched -- spec §3 design 8c's "edits highlighted
        in the feed") both bold the entire row. *col* is unused:
        xrc-windows.md's code-side note bolds the whole flagged row,
        not one cell.
        """
        if row not in self._flagged and row not in self._edited:
            return False
        attr.SetBold(True)  # noqa: FBT003 -- wx API takes a positional bool
        return True

    def _card_bitmap(self, card: str) -> Any:  # noqa: ANN401 -- wx ships no stubs
        """Return the dealt card's bitmap, or a blank cell if held."""
        key = feed_model.card_asset_key_or_none(card)
        if key is None:
            return wx.NullBitmap
        return self._card_images.bitmap(key)


class FlaggedListModel(wx.dataview.DataViewIndexListModel):  # type: ignore[misc]
    """Read-only model over flagged ``FeedRow`` rows (WS-H).

    ``# type: ignore[misc]``: the wx-ships-no-stubs note
    :class:`CrossingsFeedModel` carries -- ``DataViewIndexListModel``
    resolves to ``Any`` and mypy refuses to subclass ``Any``.

    The review notebook's "Needs Review" tab: one row per R-34 flag
    (the rows the console feed bolds), showing Plate | Lap | Lap
    time. Rows are supplied fresh each ``show_flagged``, exactly like
    :class:`CrossingsFeedModel`'s own rebuild-per-show pattern.
    """

    def __init__(self, rows: Sequence[FeedRow]) -> None:
        """Wrap *rows* (the flagged subset, newest first)."""
        super().__init__(len(rows))
        self._rows = tuple(rows)

    def GetColumnCount(self) -> int:
        """Return the flagged list's fixed three columns."""
        return len(FLAG_COLUMN_LABELS)

    def GetColumnType(self, col: int) -> str:  # noqa: ARG002 -- the model has one type
        """Return the wx variant type (plain text for every column)."""
        return "string"

    def GetValueByRow(self, row: int, col: int) -> Any:  # noqa: ANN401 -- wx ships no stubs
        """Return the cell value at *row*/*col*."""
        flagged_row = self._rows[row]
        if col == FLAG_COL_PLATE:
            return flagged_row.plate
        if col == FLAG_COL_LAP:
            return str(flagged_row.lap)
        return flagged_row.lap_time


class RidersListModel(wx.dataview.DataViewIndexListModel):  # type: ignore[misc]
    """Read-only model over ``RiderRow`` rows (WS-H).

    ``# type: ignore[misc]``: the wx-ships-no-stubs note above. The
    review notebook's "Riders" tab: Plate | Name | Team over
    ``DataSource.riders()``, with ``rider_editor``'s own dash in the
    Team cell of a solo rider. The double-click seam reads the Plate
    cell back out of this model (``set_on_open_rider``).
    """

    def __init__(self, rows: Sequence[RiderRow]) -> None:
        """Wrap *rows* in the roster's own order."""
        super().__init__(len(rows))
        self._rows = tuple(rows)

    def GetColumnCount(self) -> int:
        """Return the riders list's fixed three columns."""
        return len(RIDERS_COLUMN_LABELS)

    def GetColumnType(self, col: int) -> str:  # noqa: ARG002 -- the model has one type
        """Return the wx variant type (plain text for every column)."""
        return "string"

    def GetValueByRow(self, row: int, col: int) -> Any:  # noqa: ANN401 -- wx ships no stubs
        """Return the cell value at *row*/*col*."""
        rider = self._rows[row]
        if col == RIDERS_COL_PLATE:
            return rider.plate
        if col == RIDERS_COL_NAME:
            return rider.name
        return rider.team if rider.team is not None else _TEAM_CELL


# Fault-B (degraded-XRC-load) completeness contract: the exact frozen
# control names ``MainFrame.__init__`` resolves via ``_find`` (see the
# ``_find`` calls there). ``ui.app._load_frame_verified`` verifies every
# name in this tuple resolves in a freshly loaded ``main_frame`` and
# rebuilds once from a fresh private ``XmlResource`` if one was skipped.
# This is the single source both sides read, so the guard and
# ``__init__`` cannot silently drift apart -- keep the two in lockstep.
REQUIRED_CONTROLS: tuple[str, ...] = (
    ids.CROSSINGS_LIST,
    ids.MAIN_SPLITTER,
    ids.PLATE_INPUT,
    ids.RECORD_BTN,
    ids.LAST_CROSSING_LBL,
    ids.RIDE_NAME_LBL,
    ids.RIDE_STATUS_LBL,
    ids.CROSSINGS_COUNT_LBL,
    ids.CARDS_COUNT_LBL,
    ids.ON_COURSE_LBL,
    ids.SHOE_LBL,
    ids.START_BTN,
    ids.ARM_STOP_CHK,
    ids.STOP_BTN,
    ids.UNDO_BTN,
    ELAPSED_CLOCK_PANEL,
    REMAINING_CLOCK_PANEL,
    RIDE_STATUS_PANEL,
    ids.CLOCK_ELAPSED_LBL,
    ids.CLOCK_REMAINING_LBL,
    REVIEW_NOTEBOOK,
    ids.FLAGGED_LIST,
    ids.REVIEW_BTN,
    CONSOLE_RIDERS_LIST,
)

# The concrete wx class each REQUIRED_CONTROLS name must resolve to.
# Transcribed verbatim from ``MainFrame.__init__``'s own
# ``self._find(name, Class)`` calls below -- the one name->class
# contract the app guard (``ui.app._load_frame_verified``) and the
# harness's gate both read, so the guard can never demand a class the
# ctor does not. Keep the keys in lockstep with REQUIRED_CONTROLS
# (tests/unit/test_main_frame_guard.py pins both transcriptions).
REQUIRED_CONTROL_CLASSES: dict[str, type[wx.Window]] = {
    ids.CROSSINGS_LIST: wx.dataview.DataViewCtrl,
    ids.MAIN_SPLITTER: wx.SplitterWindow,
    ids.PLATE_INPUT: wx.TextCtrl,
    ids.RECORD_BTN: wx.Button,
    ids.LAST_CROSSING_LBL: wx.StaticText,
    ids.RIDE_NAME_LBL: wx.StaticText,
    ids.RIDE_STATUS_LBL: wx.StaticText,
    ids.CROSSINGS_COUNT_LBL: wx.StaticText,
    ids.CARDS_COUNT_LBL: wx.StaticText,
    ids.ON_COURSE_LBL: wx.StaticText,
    ids.SHOE_LBL: wx.StaticText,
    ids.START_BTN: wx.BitmapButton,
    ids.ARM_STOP_CHK: wx.CheckBox,
    ids.STOP_BTN: wx.BitmapButton,
    ids.UNDO_BTN: wx.Button,
    ELAPSED_CLOCK_PANEL: wx.Panel,
    REMAINING_CLOCK_PANEL: wx.Panel,
    RIDE_STATUS_PANEL: wx.Panel,
    ids.CLOCK_ELAPSED_LBL: wx.StaticText,
    ids.CLOCK_REMAINING_LBL: wx.StaticText,
    REVIEW_NOTEBOOK: wx.Notebook,
    ids.FLAGGED_LIST: wx.dataview.DataViewCtrl,
    ids.REVIEW_BTN: wx.Button,
    CONSOLE_RIDERS_LIST: wx.dataview.DataViewCtrl,
}


class MainFrame:
    """Code-side behaviour for ``main_frame`` (the console, 1a).

    Implements ``ConsoleView`` (module-skeletons.md's presenter
    contract). E4.4.1-E4.4.3 grew the Protocol with the four members
    the live presenter actually calls (``set_stop_enabled``,
    ``set_hide_times``, ``show_clock``, ``set_entry_locked``) -- the
    "add the member once the presenter calls it" precedent this
    class's own earlier docstring recorded for ``set_hide_times``.
    :meth:`wire_console` binds the lifecycle controls (start/arm/
    stop/undo) and the tick timer, mirroring :meth:`wire_entry`'s
    callback idiom; the app bootstrap (and the live-console harness)
    call it after construction.
    """

    def __init__(  # noqa: PLR0913, PLR0915 -- constructor: (frame, data_source, card_images, resource) + E4.4.2/E8.1.1 seams + every control it resolves
        self,
        frame: wx.Frame,
        *,
        data_source: DataSource,
        card_images: CardImageList | None = None,
        resource: Any | None = None,  # noqa: ANN401 -- wx ships no stubs
        initial_sash: int | None = None,
        initial_geometry: tuple[int, int, int, int] | None = None,
        on_layout_changed: Callable[[int | None, tuple[int, int, int, int] | None], None]
        | None = None,
    ) -> None:
        """Decorate an already-loaded ``main_frame`` window.

        Args:
            frame: The ``wx.Frame`` ``harness.load_window`` (or the
                app bootstrap) already loaded from ``main.xrc``.
            data_source: The display-data seam (module-skeletons.md
                ``ui.presenters``). This view knows only the
                :class:`~rivercrossing.ui.presenters.data_source.
                DataSource` Protocol -- the caller wires in whichever
                implementation applies (``EngineDataSource`` from
                E4.4.1; ``rivercrossing.demo`` is test-only fixture
                data since E5.4.2).
            card_images: The card bitmaps for the feed's Card column;
                defaults to the packaged deck at 1x.
            resource: The loaded ``wx.xrc.XmlResource`` the Stop
                confirm dialog is loaded from (E4.4.2); ``None`` only
                in constructions that never open that dialog.
            initial_sash: The persisted splitter sash position to
                restore at construction (E8.1.1); ``None`` keeps the
                XRC default.
            initial_geometry: The persisted frame placement
                ``(x, y, width, height)`` to restore at construction
                (E8.1.1); ``None`` keeps the canvas default size.
            on_layout_changed: Callback ``(sash, geometry)`` the app
                wires to the settings store; fired on sash change,
                move/resize and close. ``None`` (test constructions)
                reports nothing.
        """
        self.frame = frame
        self.data_source = data_source
        self.card_images = card_images if card_images is not None else default_card_images()
        self._stop_confirm_resource = resource
        self._on_layout_changed = on_layout_changed

        # Every name resolved below is also in module-level
        # REQUIRED_CONTROLS, the Fault-B completeness contract
        # ui.app._load_frame_verified verifies before this constructor
        # runs. Keep the two in lockstep.
        self.crossings_list = self._find(ids.CROSSINGS_LIST, wx.dataview.DataViewCtrl)
        self.main_splitter = self._find(ids.MAIN_SPLITTER, wx.SplitterWindow)
        self.plate_input = self._find(ids.PLATE_INPUT, wx.TextCtrl)
        self.record_btn = self._find(ids.RECORD_BTN, wx.Button)
        self.last_crossing_lbl = self._find(ids.LAST_CROSSING_LBL, wx.StaticText)
        self.ride_name_lbl = self._find(ids.RIDE_NAME_LBL, wx.StaticText)
        self.ride_status_lbl = self._find(ids.RIDE_STATUS_LBL, wx.StaticText)
        self.crossings_count_lbl = self._find(ids.CROSSINGS_COUNT_LBL, wx.StaticText)
        self.cards_count_lbl = self._find(ids.CARDS_COUNT_LBL, wx.StaticText)
        self.on_course_lbl = self._find(ids.ON_COURSE_LBL, wx.StaticText)
        self.shoe_lbl = self._find(ids.SHOE_LBL, wx.StaticText)

        # E4.4.1 lifecycle controls (start/arm/stop/undo + clock).
        self.start_btn = self._find(ids.START_BTN, wx.BitmapButton)
        self.arm_stop_chk = self._find(ids.ARM_STOP_CHK, wx.CheckBox)
        self.stop_btn = self._find(ids.STOP_BTN, wx.BitmapButton)
        self.undo_btn = self._find(ids.UNDO_BTN, wx.Button)
        # WS-D gauge slots: the dials and the status lamp are built
        # code-side inside main.xrc's placeholder panels (XRC cannot
        # author a wx.Control subclass -- the InfoBar rule above).
        self.elapsed_clock_panel = self._find(ELAPSED_CLOCK_PANEL, wx.Panel)
        self.remaining_clock_panel = self._find(REMAINING_CLOCK_PANEL, wx.Panel)
        self.ride_status_panel = self._find(RIDE_STATUS_PANEL, wx.Panel)
        self.clock_elapsed_lbl = self._find(ids.CLOCK_ELAPSED_LBL, wx.StaticText)
        self.clock_remaining_lbl = self._find(ids.CLOCK_REMAINING_LBL, wx.StaticText)
        # Reserve a fixed width for a full "H:MM:SS" timestamp so a
        # growing elapsed/remaining label can never reflow its dial
        # column (XRC has no window minsize; measured overlap on macOS
        # at default size predates the dial columns -- R-55).
        clock_width = self.clock_elapsed_lbl.GetTextExtent("23:59:59").width
        self.clock_elapsed_lbl.SetMinSize(wx.Size(clock_width, -1))
        self.clock_remaining_lbl.SetMinSize(wx.Size(clock_width, -1))
        self.elapsed_clock = self._build_clock_dial(self.elapsed_clock_panel, ELAPSED_CLOCK)
        self.remaining_clock = self._build_clock_dial(self.remaining_clock_panel, REMAINING_CLOCK)
        self.ride_status_light = StopLight(self.ride_status_panel)
        self.ride_status_light.SetName(RIDE_STATUS_LIGHT)
        self.ride_status_panel.GetSizer().Insert(0, self.ride_status_light)
        # WS-D GO/STOP glyphs. The labels are re-applied because the
        # XRC bitmap-button handler ignores <label> text (measured);
        # without them the buttons would be icon-only and unnamed to
        # assistive tech (UX-DESKTOP section 7).
        self.start_btn.SetBitmap(go_bundle().GetBitmapFor(self.start_btn))
        self.start_btn.SetLabel("Start ride")
        self.stop_btn.SetBitmap(stop_bundle().GetBitmapFor(self.stop_btn))
        self.stop_btn.SetLabel("Stop ride…")
        # R-35: Stop is gated on arm_stop_chk -- disabled at rest even
        # if the XRC ever leaves it enabled (test_menu_state pins the
        # commands-side rule; this pins the actual control).
        self.stop_btn.Enable(False)  # noqa: FBT003 -- wx API takes a positional bool

        # WS-H review notebook: the two DataView shells, their
        # columns, and the review_btn/open-rider wiring (both are pure
        # view seams; the app wires open-entry-detail later).
        self.review_notebook = self._find(REVIEW_NOTEBOOK, wx.Notebook)
        self.flagged_list = self._find(ids.FLAGGED_LIST, wx.dataview.DataViewCtrl)
        self.review_btn = self._find(ids.REVIEW_BTN, wx.Button)
        self.console_riders_list = self._find(CONSOLE_RIDERS_LIST, wx.dataview.DataViewCtrl)
        self._flagged_columns = self._build_flagged_columns()
        self._riders_columns = self._build_riders_columns()
        self._flagged_model: FlaggedListModel | None = None
        self._riders_model: RidersListModel | None = None
        self._on_open_rider: Callable[[str], None] | None = None
        self.review_btn.Bind(wx.EVT_BUTTON, lambda _event: self._on_review_clicked())
        self.console_riders_list.Bind(
            wx.dataview.EVT_DATAVIEW_ITEM_ACTIVATED, self._on_rider_activated
        )

        # LoadFrame does not honour main.xrc's <size> -- measured: the
        # frame comes back sized to the sizer's own computed minimum
        # (~429x373), not the canvas's 1100x700. SetMinSize alone only
        # stops *future* shrinking below the floor; SetSize is what
        # actually grows this window (and the splitter's client area)
        # to the canvas's documented size right now. A persisted
        # geometry (E8.1.1) replaces that default right after, so a
        # relaunch opens where the operator left the frame.
        self.frame.SetMinSize(wx.Size(*MIN_SIZE))
        self.frame.SetSize(wx.Size(*MIN_SIZE))
        if initial_geometry is not None:
            x, y, width, height = initial_geometry
            self.frame.SetPosition((x, y))
            self.frame.SetSize((width, height))

        # The console-view handle the app (and scenarios) reach the
        # view's own methods through -- the results window's
        # ``frame.presenter`` precedent (results_win.py).
        self.frame.console = self

        self._next_infobar_slot = 1  # main.xrc's spacer placeholder sits at index 0
        self.resume_infobar = self._build_infobar(RESUME_INFOBAR)
        self.reopened_infobar = self._build_infobar(REOPENED_INFOBAR)
        self.finished_infobar = self._build_infobar(FINISHED_INFOBAR)

        self._hideable_columns = self._build_columns()
        self._crossings_model: CrossingsFeedModel | None = None

        # E7.2.1: the menu-enablement binder's seam. set_state fires it
        # on every ride-state change (the epic's "existing ride-state-
        # change seam"), and show_feed fires it too -- the console
        # re-renders the feed on every record/undo/tick, so the binder
        # also refreshes the §15 count conditions (Edit Crossing's
        # "≥1 crossing", Void Card's "entry has cards") within a tick
        # of any engine change, not only on a state transition.
        self._status: RideStatus = RideStatus.DRAFT
        self._on_ride_changed: Callable[[RideStatus], None] | None = None

        # Reflow now that the size and every sizer item are final, so
        # the splitter has its real client area before a sash position
        # is read or restored.
        self.frame.Layout()

        self.main_splitter.Bind(wx.EVT_SPLITTER_SASH_POS_CHANGED, self._on_sash_changed)
        self._restore_sash_position(initial_sash)
        # E8.1.1: persist the frame's placement on move/resize and on
        # close -- the second half of the disk-backed layout store (the
        # app wires on_layout_changed to the settings module). Bound
        # here, ahead of the app's own EVT_CLOSE handler, so a quitting
        # frame saves its final layout before that handler destroys it.
        self.frame.Bind(wx.EVT_MOVE, self._on_geometry_changed)
        self.frame.Bind(wx.EVT_SIZE, self._on_geometry_changed)
        self.frame.Bind(wx.EVT_CLOSE, self._on_frame_close)

        rows = self.data_source.feed_rows()
        self.show_feed(rows)
        self.show_flagged([row for row in rows if row.flagged])
        self.show_riders(self.data_source.riders())
        self.show_counters(self.data_source.counters())

    # ------------------------------------------------------- lookups

    def _find(self, name: str, expected_type: type = wx.Window) -> Any:  # noqa: ANN401
        """Resolve one of this frame's own child controls by name.

        See :func:`find_control`'s docstring (``ui.views._support``)
        for the full measured reasoning this mirrors: an explicit
        ``self.frame`` parent scopes the lookup, and the retry loop
        settles the address-reuse hazard this wx build exhibits
        under sustained window churn.

        Raises:
            LookupError: If *name* does not resolve to an
                *expected_type* instance inside this frame, even
                after settling.
        """
        return find_control(self.frame, name, expected_type)

    # ------------------------------------------------------- InfoBars

    def _build_infobar(self, name: str) -> Any:  # noqa: ANN401 -- wx ships no stubs
        """Build one code-side InfoBar and insert it after the spacer.

        ``main.xrc``'s spacer placeholder sits at sizer index 0; each
        InfoBar is inserted right after it (and after any InfoBar
        already inserted), so the three stack in call order. A fresh
        ``wx.InfoBar`` starts hidden (measured) -- nothing further is
        needed for R-73's "hidden by default".

        Measured (wxPython 4.3.1 / wxWidgets 3.3.3, macOS, a throwaway
        probe script per this repo's convention, first reproduced
        wiring ``rider_editor_dlg``'s ``roster_infobar``, E3.2):
        ``Dismiss()``/``ShowMessage()`` on a ``wx.InfoBar`` with its
        default slide effect never returns, shown or not -- disabling
        both effects here is what keeps a future ``ShowMessage()``/
        ``Dismiss()`` call on any of these three safe.
        """
        bar = wx.InfoBar(self.frame)
        bar.SetName(name)
        bar.SetShowHideEffects(wx.SHOW_EFFECT_NONE, wx.SHOW_EFFECT_NONE)
        self.frame.GetSizer().Insert(self._next_infobar_slot, bar, 0, wx.EXPAND)
        self._next_infobar_slot += 1
        return bar

    # --------------------------------------------------------- gauges

    def _build_clock_dial(self, panel: wx.Panel, name: str) -> RaceClock:
        """Build one ``RaceClock`` into its placeholder panel (WS-D).

        Each clock slot's XRC sizer holds the caption at index 0 and
        the numeric label at index 1; the dial is inserted between
        them so the column reads caption, dial, number.
        """
        dial = RaceClock(panel)
        dial.SetName(name)
        panel.GetSizer().Insert(1, dial, 0, wx.ALIGN_CENTER_HORIZONTAL)
        return dial

    # ------------------------------------------------------- columns

    def _build_columns(self) -> tuple[Any, ...]:
        """Append the feed's seven columns in canvas order.

        Returns:
            The hide-times-affected columns (Lap time, Total), in
            column order, for :meth:`set_hide_times` to toggle.

        The Card column uses an explicit
        ``DataViewBitmapRenderer("wxBitmap")`` rather than
        ``AppendBitmapColumn``'s default: this wx build (4.3.1 /
        wxWidgets 3.3.3, probed with a throwaway script per this
        repo's convention) registers that default renderer against
        ``"wxBitmapBundle"``, which silently drops a plain
        ``wx.Bitmap`` value. The explicit ``"wxBitmap"`` renderer
        accepts ``CardImageList.bitmap()``'s values unchanged.
        """
        hideable = []
        for col, label in enumerate(feed_model.COLUMN_LABELS):
            if col == feed_model.COL_CARD:
                renderer = wx.dataview.DataViewBitmapRenderer("wxBitmap")
                column = wx.dataview.DataViewColumn(label, renderer, col)
                self.crossings_list.AppendColumn(column)
            else:
                column = self.crossings_list.AppendTextColumn(label, col)
            if col in feed_model.TIME_COLUMNS:
                hideable.append(column)
        return tuple(hideable)

    def _build_flagged_columns(self) -> tuple[Any, ...]:
        """Append the flagged list's three columns (WS-H)."""
        return tuple(
            self.flagged_list.AppendTextColumn(label, col)
            for col, label in enumerate(FLAG_COLUMN_LABELS)
        )

    def _build_riders_columns(self) -> tuple[Any, ...]:
        """Append the riders list's three columns (WS-H)."""
        return tuple(
            self.console_riders_list.AppendTextColumn(label, col)
            for col, label in enumerate(RIDERS_COLUMN_LABELS)
        )

    def set_on_open_rider(self, callback: Callable[[str], None]) -> None:
        """Register the double-click seam of the riders tab (WS-H).

        The app wires this to its open-entry-detail flow; the console
        itself only fires ``callback(plate)`` when a rider row is
        activated (double-click or Enter with the list focused).
        """
        self._on_open_rider = callback

    def focus_review_panel(self) -> None:
        """Focus the review notebook's "Needs Review" tab (WS-H).

        The Cards ▸ Review Held Cards menu route lands here -- the
        same target as ``review_btn``'s click, so the two never drift:
        show the flagged tab and focus its list. It opens nothing
        itself; the app's open-entry-detail wiring lives behind the
        riders tab's own activation seam.
        """
        self.review_notebook.SetSelection(0)
        self.flagged_list.SetFocus()

    def _on_review_clicked(self) -> None:
        """Handle ``review_btn``: the sidebar's "Review…" affordance.

        Deferring to :meth:`focus_review_panel` keeps the button's
        behavior and the menu route's behavior one implementation
        (WS-H).
        """
        self.focus_review_panel()

    def _on_rider_activated(self, event: Any) -> None:  # noqa: ANN401 -- wx ships no stubs
        """Fire the open-rider seam with the activated row's plate."""
        if self._riders_model is None:
            return
        row = self._riders_model.GetRow(event.GetItem())
        if row == wx.NOT_FOUND:
            return
        plate = self._riders_model.GetValueByRow(row, RIDERS_COL_PLATE)
        if self._on_open_rider is not None:
            self._on_open_rider(plate)

    def set_hide_times(self, *, hide: bool) -> None:
        """Toggle the Lap time/Total columns per R-37.

        The clock (``clock_elapsed_lbl``/``clock_remaining_lbl``) is
        untouched -- R-37 keeps it visible regardless of this setting.
        """
        for column in self._hideable_columns:
            column.SetHidden(hide)

    # -------------------------------------------------------- splitter

    def _restore_sash_position(self, initial_sash: int | None) -> None:
        """Apply the persisted sash position, if saved (E8.1.1)."""
        if initial_sash is not None:
            self.main_splitter.SetSashPosition(initial_sash)

    def persist_layout(self) -> None:
        """Report the current sash position and frame geometry (E8.1.1).

        Fires the constructor's ``on_layout_changed`` callback, which
        the app bootstrap wires to the settings store; an unwired
        frame (test constructions) reports nothing. wx only fires the
        sash event from genuine user drag input, never from a
        programmatic ``SetSashPosition`` (measured), so tests call
        this directly instead (CODINGSTANDARDS-UX-DESKTOP.md section
        6: sash positions must persist across restarts). The
        move/size/close handlers all route through this one seam.
        """
        if self._on_layout_changed is None:
            return
        position = self.frame.GetPosition()
        size = self.frame.GetSize()
        geometry = (position.x, position.y, size.width, size.height)
        self._on_layout_changed(self.main_splitter.GetSashPosition(), geometry)

    def _on_sash_changed(self, event: Any) -> None:  # noqa: ANN401 -- wx ships no stubs
        """Persist a real, user-driven sash drag."""
        event.Skip()
        self.persist_layout()

    def _on_geometry_changed(self, event: Any) -> None:  # noqa: ANN401 -- wx ships no stubs
        """Persist a move or resize, then let the event continue.

        No debounce: the settings file is a few hundred bytes and the
        write is an atomic replace, so a drag's dozens of events cost
        less than a layout-save timer's destroy hazard would (the
        ``_tick_timer`` segfault precedent).
        """
        event.Skip()
        self.persist_layout()

    def _on_frame_close(self, event: Any) -> None:  # noqa: ANN401 -- wx ships no stubs
        """Persist the layout, then let the app's close flow run.

        ``event.Skip()`` is what lets the app bootstrap's own
        ``EVT_CLOSE`` handler (bound after this one) still run.
        """
        self.persist_layout()
        event.Skip()

    # ----------------------------------------------------- ConsoleView

    def show_feed(self, rows: list[FeedRow]) -> None:
        """Render the crossings feed, newest first (ConsoleView).

        Also fires the E7.2.1 menu-binder seam: the feed re-renders on
        every record/undo/tick, so §15 count conditions refresh within
        a tick of any engine change (see the constructor comment).
        """
        self._crossings_model = CrossingsFeedModel(rows, self.card_images)
        self.crossings_list.AssociateModel(self._crossings_model)
        self._notify_ride_changed()

    def show_flagged(self, rows: list[FeedRow]) -> None:
        """Render the review notebook's flagged rows (ConsoleView).

        WS-H: the presenter feeds the flagged subset of the feed here
        (its ``_refresh_feed``), and the view rebuilds the model like
        :meth:`show_feed` does -- fresh rows each call keeps the
        row-count bookkeeping trivial.
        """
        self._flagged_model = FlaggedListModel(rows)
        self.flagged_list.AssociateModel(self._flagged_model)

    def show_riders(self, rows: list[RiderRow]) -> None:
        """Render the review notebook's riders rows (ConsoleView).

        WS-H: fed by the presenter's ``_refresh_riders`` on the tick
        (``DataSource.riders()``), and once at construction.
        """
        self._riders_model = RidersListModel(rows)
        self.console_riders_list.AssociateModel(self._riders_model)

    def show_counters(self, c: Counters) -> None:
        """Render the four counter chips (ConsoleView)."""
        self.crossings_count_lbl.SetLabel(_format_count(c.crossings))
        self.cards_count_lbl.SetLabel(_format_count(c.cards_dealt))
        self.on_course_lbl.SetLabel(_format_count(c.on_course))
        self.shoe_lbl.SetLabel(f"{c.shoe_remaining}/{c.shoe_total}")

    def flash_crossing(self, r: FeedRow) -> None:
        """Highlight the just-recorded crossing (ConsoleView)."""
        self.last_crossing_lbl.SetLabel(
            f"✓ {r.plate} · {r.entry} · Lap {r.lap} · {r.lap_time} · dealt {r.card}"
        )

    def set_state(self, status: RideStatus) -> None:
        """Reflect the ride's lifecycle state (ConsoleView).

        The status label and record-crossing row enablement (A4:
        ``record_btn`` tracks ``plate_input``, both live only in
        RUNNING), and the REOPENED corrections banner: REOPENED is a
        corrections-only state (spec §3, R-36), so the console shows
        ``reopened_infobar`` to say entry is off and corrections are
        on (E5.2.2), and dismisses it for every other status.

        This is the E7.2.1 menu-binder's "ride-state-change seam":
        every presenter state transition (start/stop/finish/reopen)
        lands here, and the binder re-applies the §15 enablement.
        WS-D adds the status lamp: the same state transition drives
        the ``StopLight`` through ``console.stop_light_mode``.
        """
        self.ride_status_lbl.SetLabel(status.value.upper())
        self.ride_status_light.set_mode(stop_light_mode(status))
        running = status == RideStatus.RUNNING
        self.plate_input.Enable(running)
        self.record_btn.Enable(running)
        if status is RideStatus.REOPENED:
            self.reopened_infobar.ShowMessage(REOPENED_BANNER, wx.ICON_INFORMATION)
        else:
            self.reopened_infobar.Dismiss()
        self._status = status
        self._notify_ride_changed()

    def show_ride_name(self, name: str) -> None:
        """Render the open ride's name (ConsoleView, E9.1.4).

        ``ride_name_lbl`` is the frozen design's ride-identity line
        (xrc-windows.md section A); every console switch onto a
        store ride renders the ride's name here -- the library Open
        and the New Ride flow alike.
        """
        self.ride_name_lbl.SetLabel(name)

    def set_on_ride_changed(self, callback: Callable[[RideStatus], None]) -> None:
        """Register the menu-binder callback fired on ride changes.

        The app bootstrap wires this to its ``_apply_menu_state``;
        fired from :meth:`set_state` (state transitions) and
        :meth:`show_feed` (count-condition refreshes). Not part of the
        ``ConsoleView`` Protocol -- it is an app-level seam, set once
        after construction.
        """
        self._on_ride_changed = callback

    def _notify_ride_changed(self) -> None:
        """Fire the binder seam, if one is registered."""
        if self._on_ride_changed is not None:
            self._on_ride_changed(self._status)

    def focus_entry(self) -> None:
        """Return focus to the plate entry field (ConsoleView)."""
        self.plate_input.SetFocus()

    def show_notice(self, text: str) -> None:
        """Post *text* to the status bar's first field (ConsoleView)."""
        self.frame.SetStatusText(text, 0)

    def clear_entry(self) -> None:
        """Empty the plate entry field (ConsoleView).

        ``ChangeValue``, not ``SetValue``: wx's own documented
        contract is that ``ChangeValue`` does not fire ``EVT_TEXT``,
        so clearing the field after a submit cannot loop back into
        any future EVT_TEXT-driven validation.
        """
        self.plate_input.ChangeValue("")

    def wire_entry(self, on_submit: Callable[[str], None]) -> None:
        """Bind Enter and Record to *on_submit* with the field's text.

        Binds ``EVT_TEXT_ENTER`` (``plate_input`` carries
        ``wxTE_PROCESS_ENTER``) and ``EVT_BUTTON`` (``record_btn``)
        to the same call. Neither handler calls ``event.Skip()``,
        and ``record_btn`` never gets ``SetDefault()``: with
        ``wxTE_PROCESS_ENTER``, ``Skip()`` would fall through to
        wx's own default-button dispatch and fire a second submit
        for the one Enter keypress.

        The callback is stored as :attr:`_on_submit` and every
        handler routes through it, so :meth:`set_presenter` can swap
        the console onto a new ride without rebinding (E5.4.1's
        library Open).
        """
        self._on_submit = on_submit

        def _submit(_event: Any) -> None:  # noqa: ANN401 -- wx ships no stubs
            self._on_submit(self.plate_input.GetValue())

        self.plate_input.Bind(wx.EVT_TEXT_ENTER, _submit)
        self.record_btn.Bind(wx.EVT_BUTTON, _submit)

    def play(self, cue: Cue) -> None:
        """Play the audio cue for the given event (ConsoleView, R-31).

        Delegates to ``ui.sound``'s default player (E4.4.3); the
        player is wx-lazy and never blocks the entry field (spec §10).
        """
        sound.play(cue)

    def set_stop_enabled(self, *, enabled: bool) -> None:
        """Enable or disable the Stop button (ConsoleView, R-35).

        Disarming also unticks ``arm_stop_chk`` so the checkbox
        visibly reflects the presenter's auto-clear (after use or
        timeout); ``SetValue`` fires no ``EVT_CHECKBOX`` (measured
        harness convention), so this cannot loop back into the
        presenter.
        """
        self.stop_btn.Enable(enabled)
        if not enabled:
            self.arm_stop_chk.SetValue(False)  # noqa: FBT003 -- wx API takes a positional bool

    def show_clock(self, elapsed: str, remaining: str) -> None:
        """Render the ride clock's numeric labels (ConsoleView, R-30).

        The labels sit under the WS-D dials; ``clock_remaining_lbl``
        carries no canvas label, and the elapsed label's default
        ``0:00:00`` comes from main.xrc.
        """
        self.clock_elapsed_lbl.SetLabel(elapsed)
        self.clock_remaining_lbl.SetLabel(remaining)
        self.frame.Layout()

    def set_clock_fractions(self, *, elapsed_frac: float, remaining_frac: float) -> None:
        """Drive the two gauge-clock dials (ConsoleView, WS-D).

        The elapsed dial fills toward 1.0 as the ride runs, the
        remaining dial drains toward 0.0; both hand positions come
        pre-clamped from the presenter's planned-duration math.
        """
        self.elapsed_clock.set_fraction(elapsed_frac)
        self.remaining_clock.set_fraction(remaining_frac)

    def set_entry_locked(self, *, locked: bool) -> None:
        """Lock or unlock the plate entry row (ConsoleView, R-35).

        Stop is a guard, not a state: after ``engine.stop()`` the ride
        still reads RUNNING, so ``set_state`` would re-enable the
        entry row -- this is the "only confirming locks the entry
        field" channel on top of it.
        """
        self.plate_input.Enable(not locked)
        self.record_btn.Enable(not locked)

    def wire_console(self, presenter: ConsolePresenter) -> None:
        """Bind the lifecycle controls and tick timer to *presenter*.

        Mirrors :meth:`wire_entry`'s callback idiom: Start Ride,
        the Arm checkbox, Stop Ride (through the confirm dialog,
        :meth:`_on_stop_clicked`) and Undo each forward to the
        presenter, and a 1 s ``wx.Timer`` drives ``presenter.tick()``
        (feed/counters/clock refresh + R-35's 10 s arm auto-clear).

        The presenter is stored as :attr:`_presenter` and every
        handler routes through it, so :meth:`set_presenter` can swap
        the console onto a store-loaded ride without rebinding the
        controls or the timer (E5.4.1's library Open).
        """
        self._presenter = presenter
        self.start_btn.Bind(wx.EVT_BUTTON, lambda _event: self._presenter.on_start())
        self.arm_stop_chk.Bind(
            wx.EVT_CHECKBOX,
            lambda _event: self._presenter.on_arm_stop(armed=self.arm_stop_chk.GetValue()),
        )
        self.stop_btn.Bind(wx.EVT_BUTTON, lambda _event: self._on_stop_clicked())
        self.undo_btn.Bind(wx.EVT_BUTTON, lambda _event: self._presenter.on_undo())
        self._tick_timer = wx.Timer(self.frame)
        self.frame.Bind(wx.EVT_TIMER, lambda _event: self._presenter.tick(), self._tick_timer)
        self._tick_timer.Start(_TICK_MS)
        # Stop the timer with the frame: a running wx.Timer whose owner
        # was destroyed keeps its native timer registered, and the next
        # wxSafeYield dispatches wxTimerImpl::SendEvent against the
        # freed owner -- the measured segfault behind the functional
        # suite's "worker crashed" flake (reproduced deterministically:
        # build frame -> destroy -> SafeYield past the tick period).
        self.frame.Bind(wx.EVT_WINDOW_DESTROY, lambda _event: self._tick_timer.Stop())

    def set_presenter(self, presenter: ConsolePresenter) -> None:
        """Swap the console's bound presenter (E5.4.1 library Open).

        :meth:`wire_entry`/:meth:`wire_console` route every handler
        through :attr:`_on_submit`/:attr:`_presenter`, so replacing
        those two references rewires the whole console -- plate entry,
        start/arm/stop/undo, the tick timer -- without rebinding any
        control or starting a second timer. The caller then re-renders
        state/feed/counters from the new presenter's source.
        """
        self._on_submit = presenter.on_plate_entered
        self._presenter = presenter

    def _on_stop_clicked(self) -> None:
        """Handle Stop Ride: R-35's confirm, then ``on_stop_confirmed``.

        Loads ``stop_confirm_dlg`` from the constructor's resource and
        shows it through ``dialogs.run_dialog`` -- the one entry point
        every dialog in this codebase shows through -- so the default
        + focused Cancel is honoured (test_dialog_behavior pins it on
        the raw dialog) and only ``wxID_OK`` ("Stop ride") confirms.
        A construction with no resource (a screen that never opens the
        dialog) posts a notice rather than silently stopping.

        # logic-coverage-exempt: T-3 -- the two ``is None`` guards are
        # defensive for constructions that never open the dialog (the
        # shared read-only fixtures); every live construction supplies
        # the resource and the OK/Cancel arms are driven functionally.
        """
        from rivercrossing.ui.views import dialogs  # noqa: PLC0415 -- deferred, see app.py

        if self._stop_confirm_resource is None:
            self.show_notice("Stop confirm unavailable")
            return
        dialog = self._stop_confirm_resource.LoadDialog(None, ids.STOP_CONFIRM_DLG)
        if dialog is None:
            self.show_notice("Stop confirm unavailable")
            return
        try:
            result = dialogs.run_dialog(dialog, opener=self.stop_btn)
        finally:
            if not dialog.IsBeingDeleted():
                dialog.Destroy()
        if result == wx.ID_OK:
            self._presenter.on_stop_confirmed()


def _format_count(value: int) -> str:
    """Render *value* with a space as the thousands separator.

    Matches the canvas exactly: 1124 -> "1 124", 42 -> "42".
    """
    return f"{value:,}".replace(",", " ")
