# SPDX-License-Identifier: GPL-3.0-only
"""Generate ``ui/ids.py`` from the project's XRC files (R-05).

XRC control names are the single frozen name registry (spec.md
section 15b): every ``name`` attribute on an ``<object>`` element
becomes one ``UPPER_SNAKE = "snake_case"`` constant. A name must be
unique within one top-level window (frame, dialog, menubar); the
same name recurring across *different* windows -- ``plate_input``
in ``main_frame``, ``edit_crossing_dlg`` and ``manual_deal_dlg`` --
collapses to a single constant.

    python tools/gen_ids.py --write   # regenerate ui/ids.py
    python tools/gen_ids.py --check   # fail the build on drift

Both flags accept ``--xrc-dir``/``--out`` overrides so tests can
point the generator at fixture files instead of the real tree.
"""

import argparse
import ast
import sys
from collections import Counter
from collections.abc import (  # noqa: TC003 -- dev CLI, no perf-sensitive import path
    Iterable,
    Sequence,
)
from pathlib import Path
from typing import NamedTuple
from xml.etree import ElementTree as ET

STOCK_IDS: frozenset[str] = frozenset(
    {
        "wxID_OK",
        "wxID_CANCEL",
        "wxID_CLOSE",
        "wxID_DELETE",
        "wxID_OPEN",
        "wxID_NEW",
        "wxID_EXIT",
        "wxID_ABOUT",
        "wxID_PREFERENCES",
    }
)

# spec.md section 15b, verbatim: "suffix by role -- `_frame _dlg
# _panel _lbl _input _btn _chk _radio _choice _list _picker _spin
# _infobar`".
SPEC_KNOWN_SUFFIXES: tuple[str, ...] = (
    "_frame",
    "_dlg",
    "_panel",
    "_lbl",
    "_input",
    "_btn",
    "_chk",
    "_radio",
    "_choice",
    "_list",
    "_picker",
    "_spin",
    "_infobar",
)

# In active use on the xrc-windows.md canvas (main_menubar,
# main_statusbar, audit_search, about_logo_bmp, gorba_link,
# selftest_output, main_splitter) but never named in section 15b's
# own suffix sentence -- extension, not part of the frozen text.
# Revisit when section 15b is next amended (Phase 7).
CANVAS_KNOWN_SUFFIXES: tuple[str, ...] = (
    "_menubar",
    "_statusbar",
    "_search",
    "_bmp",
    "_link",
    "_output",
    "_splitter",
)

KNOWN_SUFFIXES: tuple[str, ...] = SPEC_KNOWN_SUFFIXES + CANVAS_KNOWN_SUFFIXES

# spec.md section 15b, same sentence as the suffix list: "menu items
# `mi_<action>`" -- a *prefix* convention, never suffix-checked.
MENU_ITEM_PREFIX = "mi_"

_HEADER = '''# SPDX-License-Identifier: GPL-3.0-only
"""XRC control name registry.

Generated by tools/gen_ids.py from the project's .xrc files
(spec.md section 15b) -- never hand-edited. Regenerate with
``nox -s gen_ids``; ``nox -s ids_drift`` fails the build on
any disagreement (R-05).
"""'''

_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_XRC_DIR = _ROOT / "src" / "rivercrossing" / "ui" / "xrc"
DEFAULT_OUT = _ROOT / "src" / "rivercrossing" / "ui" / "ids.py"


class DuplicateXrcNameError(ValueError):
    """Raised when one top-level XRC window reuses a control name."""


class InvalidXrcNameError(ValueError):
    """Raised when an XRC name cannot become a Python identifier."""


class ScanResult(NamedTuple):
    """Unique control names found, plus suffix-convention warnings."""

    names: tuple[str, ...]
    warnings: tuple[str, ...]


def iter_xrc_files(xrc_dir: Path) -> list[Path]:
    """List every ``.xrc`` file in *xrc_dir*, sorted for determinism."""
    return sorted(xrc_dir.glob("*.xrc"))


def _top_level_windows(root: ET.Element) -> list[ET.Element]:
    """Return the direct ``<object>`` children of an XRC ``<resource>``.

    Each one is its own name namespace: a control name must be
    unique within it, but may recur in a different top-level window.
    """
    return [child for child in root if child.tag == "object"]


def _names_in_window(window: ET.Element) -> list[str]:
    """List every non-stock ``name`` attribute in *window*'s subtree."""
    names = []
    for elem in window.iter("object"):
        name = elem.get("name")
        if name is not None and name not in STOCK_IDS:
            names.append(name)
    return names


def _check_no_duplicates(window_name: str, names: list[str], source: Path) -> None:
    """Raise if *names* repeats a control name within one window."""
    dupes = sorted(name for name, count in Counter(names).items() if count > 1)
    if dupes:
        msg = f"duplicate name(s) in {window_name!r} ({source.name}): {', '.join(dupes)}"
        raise DuplicateXrcNameError(msg)


def _suffix_warnings(names: Iterable[str]) -> list[str]:
    """List a warning for each name with an unrecognised suffix.

    See spec.md section 15b for the frozen suffix list. A name
    matching the ``mi_`` menu-item prefix is never suffix-checked --
    the prefix convention wins even if the tail is also unknown.
    """
    return [
        f"{name!r} does not end with a known suffix {KNOWN_SUFFIXES}"
        for name in names
        if not name.startswith(MENU_ITEM_PREFIX) and not name.endswith(KNOWN_SUFFIXES)
    ]


def scan_xrc_directory(xrc_dir: Path) -> ScanResult:
    """Parse every ``.xrc`` file in *xrc_dir* into a ``ScanResult``.

    Raises:
        DuplicateXrcNameError: A control name repeats within one
            top-level window.
    """
    all_names: set[str] = set()
    for path in iter_xrc_files(xrc_dir):
        root = ET.parse(path).getroot()  # noqa: S314 -- our own .xrc, not attacker input
        for window in _top_level_windows(root):
            # logic-coverage-exempt: T-3 unreachable for loadable XRC
            # -- LoadFrame/LoadDialog/LoadMenuBar all require a name
            # to load a window at all, so a nameless top-level object
            # can never appear in valid input; the fallback below is
            # unreachable and untested by design.
            window_name = window.get("name") or f"{path.name}#unnamed"
            names = _names_in_window(window)
            _check_no_duplicates(window_name, names, path)
            all_names.update(names)
    sorted_names = tuple(sorted(all_names))
    return ScanResult(names=sorted_names, warnings=tuple(_suffix_warnings(sorted_names)))


def _constant_name(name: str) -> str:
    """Convert one XRC name to its ``UPPER_SNAKE`` constant name.

    Raises:
        InvalidXrcNameError: *name* cannot become a Python identifier.
    """
    constant = name.upper()
    if not constant.isidentifier():
        msg = f"{name!r} is not a valid Python identifier"
        raise InvalidXrcNameError(msg)
    return constant


def render_ids_module(names: Iterable[str]) -> str:
    """Render the full ``ids.py`` source text for *names*.

    Raises:
        InvalidXrcNameError: A name cannot become a Python identifier.
    """
    lines = [f'{_constant_name(name)} = "{name}"' for name in names]
    body = "\n".join(lines)
    return f"{_HEADER}\n\n{body}\n" if body else f"{_HEADER}\n"


def _parse_constant_values(source: str) -> set[str]:
    """Return the string values assigned by top-level constants."""
    tree = ast.parse(source)
    values: set[str] = set()
    for node in tree.body:
        if not isinstance(node, ast.Assign):
            continue
        # logic-coverage-exempt: T-3 unreachable in this tool's own
        # output -- render_ids_module only ever emits NAME = "string"
        # constants, so a top-level Assign with a non-string value
        # never occurs in a file this generator produced.
        if not isinstance(node.value, ast.Constant) or not isinstance(node.value.value, str):
            continue
        values.add(node.value.value)
    return values


def _existing_constant_values(out_path: Path) -> set[str]:
    """Return the string values already assigned in *out_path*."""
    if not out_path.exists():
        return set()
    return _parse_constant_values(out_path.read_text(encoding="utf-8"))


def diff_against_existing(out_path: Path, names: Iterable[str]) -> list[str]:
    """List drift between *out_path* and *names*, in both directions."""
    current = set(names)
    existing = _existing_constant_values(out_path)
    missing = sorted(current - existing)
    stale = sorted(existing - current)
    return [f"xrc name has no constant: {name!r}" for name in missing] + [
        f"constant has no xrc name: {name!r}" for name in stale
    ]


def write_ids_module(out_path: Path, xrc_dir: Path) -> ScanResult:
    """Regenerate *out_path* from *xrc_dir*; return the scan result."""
    result = scan_xrc_directory(xrc_dir)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(render_ids_module(result.names), encoding="utf-8")
    return result


def check_ids_module(out_path: Path, xrc_dir: Path) -> tuple[ScanResult, list[str]]:
    """Scan *xrc_dir* and diff it against *out_path*'s constants."""
    result = scan_xrc_directory(xrc_dir)
    return result, diff_against_existing(out_path, result.names)


def _build_parser() -> argparse.ArgumentParser:
    """Build the ``--write``/``--check`` argument parser."""
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="regenerate ids.py")
    mode.add_argument("--check", action="store_true", help="fail the build on drift")
    parser.add_argument("--xrc-dir", type=Path, default=DEFAULT_XRC_DIR)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    return parser


def _run_write(out_path: Path, xrc_dir: Path) -> int:
    """Regenerate *out_path* and report what was written."""
    result = write_ids_module(out_path, xrc_dir)
    for warning in result.warnings:
        print(f"warning: {warning}")
    print(f"wrote {len(result.names)} names to {out_path}")
    return 0


def _run_check(out_path: Path, xrc_dir: Path) -> int:
    """Report drift between *out_path* and *xrc_dir*; 0 if none."""
    result, diffs = check_ids_module(out_path, xrc_dir)
    for warning in result.warnings:
        print(f"warning: {warning}")
    if not diffs:
        print(f"{out_path} matches {len(result.names)} names in {xrc_dir}")
        return 0
    for line in diffs:
        print(f"drift: {line}")
    return 1


def main(argv: Sequence[str] | None = None) -> int:
    """Run the CLI: dispatch to ``--write`` or ``--check``."""
    args = _build_parser().parse_args(argv)
    try:
        if args.write:
            return _run_write(args.out, args.xrc_dir)
        return _run_check(args.out, args.xrc_dir)
    except (DuplicateXrcNameError, InvalidXrcNameError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main())
