# SPDX-License-Identifier: GPL-3.0-only
"""Vendor the results-page CSS and Barlow font subsets (E6.2.1).

The results page (``base.html.j2``) is a self-contained offline file:
its styles are compiled once, at package build, by the pinned
Tailwind v4 CLI against the frozen templates (``theme.css`` + the
``.j2`` files' classes), and its Barlow typefaces ship as base64
``@font-face`` blocks. This generator produces both committed
artifacts under ``src/rivercrossing/htmlexport/templates/``:

* ``compiled_css`` -- the minified Tailwind output with a provenance
  header recording theme.css's sha256 (the TB-7 staleness gate: CI
  fails if the committed CSS was built from different source).
* ``fonts_css`` -- ``@font-face`` blocks embedding the five Barlow
  woff2 subsets, deterministically ordered, no timestamps.

    python tools/gen_css.py --write   # regenerate both artifacts
    python tools/gen_css.py --check   # fail the build on drift

Both flags accept ``--templates-dir``/``--out-dir`` overrides so
tests can point the generator at fixture files instead of the real
tree. ``--check`` passes vacuously when the templates are absent --
the same guard ``nox -s ids_drift`` applies to the .xrc tree.
"""

import argparse
import base64
import hashlib
import shutil
import subprocess
import sys
import tempfile
from collections.abc import Sequence  # noqa: TC003 -- dev CLI, no perf-sensitive import path
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_TEMPLATES_DIR = _ROOT / "src" / "rivercrossing" / "htmlexport" / "templates"
DEFAULT_OUT_DIR = DEFAULT_TEMPLATES_DIR

COMPILED_CSS_NAME = "compiled_css"
FONTS_CSS_NAME = "fonts_css"

# The three shipped template files; the wrapper below needs theme.css
# (it holds the @theme tokens and custom rules), and the .j2 files are
# scanned by the CLI's automatic content detection for utility classes.
INPUT_TEMPLATE_FILES: tuple[str, ...] = ("base.html.j2", "macros.html.j2", "theme.css")

# Pinned CLI, matching package.json's devDependencies (@tailwindcss/cli
# 4.3.3). The provenance header below names this version so a pin bump
# shows up in the regenerated artifact.
_TAILWIND_CLI = _ROOT / "node_modules" / ".bin" / "tailwindcss"
_TAILWIND_VERSION = "4.3.3"

# The wrapper is what makes theme.css a valid Tailwind v4 input: a
# bare @theme file has no `@import "tailwindcss";`, so Tailwind would
# not treat it as a stylesheet entry point.
_WRAPPER_CSS = '@import "tailwindcss";\n@import "./theme.css";\n'

# (filename, font family, font weight) -- the frozen typeface set, in
# stable output order (Spec section 8: Barlow 400/500/700 and Barlow
# Condensed 400/600, always upright).
FONT_FILES: tuple[tuple[str, str, int], ...] = (
    ("barlow-400.woff2", "Barlow", 400),
    ("barlow-500.woff2", "Barlow", 500),
    ("barlow-700.woff2", "Barlow", 700),
    ("barlow-condensed-400.woff2", "Barlow Condensed", 400),
    ("barlow-condensed-600.woff2", "Barlow Condensed", 600),
)

_COMPILED_CSS_HEADER = (
    "/* rivercrossing compiled_css — generated by tools/gen_css.py; "
    "source theme.css sha256:{sha256}; tailwindcss {version} */"
)


class TailwindCliMissingError(RuntimeError):
    """Raised when the pinned Tailwind CLI is not installed."""


class TailwindCompileError(RuntimeError):
    """Raised when the Tailwind CLI exits non-zero."""


def _sha256_hex(path: Path) -> str:
    """Return the lowercase hex sha256 of *path*."""
    return hashlib.sha256(path.read_bytes()).hexdigest()


def data_font_uri(data: bytes) -> str:
    """Return the ``src`` value for one woff2 ``@font-face``."""
    encoded = base64.b64encode(data).decode("ascii")
    return f'url(data:font/woff2;base64,{encoded}) format("woff2")'


def render_font_face(family: str, weight: int, src: str) -> str:
    """Render one ``@font-face`` block for *family*/*weight*/*src*."""
    return (
        "@font-face {\n"
        f'  font-family: "{family}";\n'
        "  font-style: normal;\n"
        f"  font-weight: {weight};\n"
        f"  src: {src};\n"
        "}"
    )


def _fonts_provenance(fonts_dir: Path) -> str:
    """Return the provenance comment naming every font file's sha256."""
    parts = " ".join(
        f"{name} sha256:{_sha256_hex(fonts_dir / name)}" for name, _family, _weight in FONT_FILES
    )
    return f"/* rivercrossing fonts_css — generated by tools/gen_css.py; {parts} */"


def render_fonts_css(fonts_dir: Path) -> str:
    """Render ``@font-face`` blocks for the woff2 files in *fonts_dir*.

    Deterministic: files are read in :data:`FONT_FILES` order, the
    provenance comment records each file's sha256, and no timestamps
    or paths leak into the output.
    """
    blocks = [_fonts_provenance(fonts_dir)]
    for name, family, weight in FONT_FILES:
        uri = data_font_uri((fonts_dir / name).read_bytes())
        blocks.append(render_font_face(family, weight, uri))
    return "\n".join(blocks) + "\n"


def render_compiled_css(compiled: bytes, theme_sha256: str) -> bytes:
    """Prefix the Tailwind output with the TB-7 provenance header."""
    header = _COMPILED_CSS_HEADER.format(sha256=theme_sha256, version=_TAILWIND_VERSION).encode(
        "utf-8"
    )
    return header + b"\n" + compiled


def _run_tailwind_cli(argv: Sequence[str]) -> bytes:
    """Run the pinned Tailwind CLI, returning its stdout bytes.

    The CLI writes the compiled CSS to the ``-o`` output file; the
    caller reads that file for the artifact bytes. The return value
    (stdout) is empty in that mode -- the seam exists so tests can
    substitute the binary without Node being installed.

    Raises:
        TailwindCliMissingError: The pinned CLI is not installed.
        TailwindCompileError: The CLI exited non-zero.
    """
    if not _TAILWIND_CLI.is_file():
        msg = (
            f"pinned Tailwind CLI not found at {_TAILWIND_CLI} -- "
            f"run `npm install` first (pins @tailwindcss/cli "
            f"{_TAILWIND_VERSION})"
        )
        raise TailwindCliMissingError(msg)
    try:
        proc = subprocess.run(  # noqa: S603 -- absolute path, fixed argv list, no shell
            [str(_TAILWIND_CLI), *argv],
            cwd=_ROOT,
            capture_output=True,
            check=True,
        )
    except subprocess.CalledProcessError as exc:
        stderr = exc.stderr.decode("utf-8", errors="replace").strip()
        msg = f"tailwindcss exited {exc.returncode}: {stderr}"
        raise TailwindCompileError(msg) from exc
    return proc.stdout


def _make_work_dir() -> Path:
    """Create a scratch dir under build/ for the wrapper + output.

    The wrapper does ``@import "tailwindcss";``, which Node resolves
    by walking up from the importing file, so the scratch dir must sit
    inside the repo (under the gitignored build/ tree) for the pinned
    CLI to find its own package.
    """
    build_dir = _ROOT / "build"
    build_dir.mkdir(parents=True, exist_ok=True)
    return Path(tempfile.mkdtemp(prefix="gen_css-", dir=build_dir))


def build_artifacts(templates_dir: Path, work_dir: Path) -> tuple[bytes, bytes]:
    """Compile and render both artifacts from *templates_dir*.

    *work_dir* is a caller-owned scratch directory that receives the
    Tailwind wrapper, copies of the three input templates, and the
    CLI's output file. ``--cwd`` pins the CLI to *work_dir*, so the
    automatic content detection scans exactly those three files --
    nothing else in the repo. Measured: the repo-wide fallback scan
    feeds the committed artifacts (and any stray non-gitignored file)
    back into the candidate set, so a fresh build never reproduces the
    committed ``compiled_css`` and the drift gate can never pass.
    Returns ``(compiled_css, fonts_css)`` bytes, deterministic for a
    given tree.

    Raises:
        TailwindCliMissingError: The pinned CLI is not installed.
        TailwindCompileError: The CLI exited non-zero.
    """
    work_dir.mkdir(parents=True, exist_ok=True)
    (work_dir / "wrapper.css").write_text(_WRAPPER_CSS, encoding="utf-8")
    for name in INPUT_TEMPLATE_FILES:
        shutil.copyfile(templates_dir / name, work_dir / name)
    _run_tailwind_cli(
        ["--cwd", str(work_dir), "-i", "wrapper.css", "-o", "compiled.css", "--minify"]
    )
    compiled_css = render_compiled_css(
        (work_dir / "compiled.css").read_bytes(), _sha256_hex(templates_dir / "theme.css")
    )
    fonts_css = render_fonts_css(templates_dir / "fonts").encode("utf-8")
    return compiled_css, fonts_css


def write_artifacts(templates_dir: Path, out_dir: Path) -> tuple[Path, Path]:
    """Regenerate both artifacts into *out_dir* from *templates_dir*.

    Returns the two paths written. Byte-identical regeneration is the
    contract: the same tree always produces the same bytes.
    """
    work_dir = _make_work_dir()
    try:
        compiled_css, fonts_css = build_artifacts(templates_dir, work_dir)
    finally:
        shutil.rmtree(work_dir, ignore_errors=True)
    out_dir.mkdir(parents=True, exist_ok=True)
    compiled_path = out_dir / COMPILED_CSS_NAME
    fonts_path = out_dir / FONTS_CSS_NAME
    compiled_path.write_bytes(compiled_css)
    fonts_path.write_bytes(fonts_css)
    return compiled_path, fonts_path


def _templates_present(templates_dir: Path) -> bool:
    """Return True when every generator input template exists."""
    return all((templates_dir / name).is_file() for name in INPUT_TEMPLATE_FILES)


def drift_lines(committed: Path, regenerated: bytes, name: str) -> list[str]:
    """Return drift lines for one artifact, [] when identical."""
    if not committed.exists():
        return [f"{name} missing from {committed.parent}"]
    if committed.read_bytes() != regenerated:
        return [f"{name} drifted from {committed}"]
    return []


def check_artifacts(templates_dir: Path, out_dir: Path) -> list[str]:
    """Regenerate from *templates_dir* and diff against *out_dir*.

    Runs the real Tailwind CLI via the seam; this single call is both
    the CI compile and the TB-7 staleness gate. Returns drift lines,
    [] when the committed artifacts match a fresh build.
    """
    work_dir = _make_work_dir()
    try:
        compiled_css, fonts_css = build_artifacts(templates_dir, work_dir)
    finally:
        shutil.rmtree(work_dir, ignore_errors=True)
    return [
        *drift_lines(out_dir / COMPILED_CSS_NAME, compiled_css, COMPILED_CSS_NAME),
        *drift_lines(out_dir / FONTS_CSS_NAME, fonts_css, FONTS_CSS_NAME),
    ]


def _build_parser() -> argparse.ArgumentParser:
    """Build the ``--write``/``--check`` argument parser."""
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="regenerate the vendored CSS")
    mode.add_argument("--check", action="store_true", help="fail the build on drift")
    parser.add_argument("--templates-dir", type=Path, default=DEFAULT_TEMPLATES_DIR)
    parser.add_argument("--out-dir", type=Path, default=DEFAULT_OUT_DIR)
    return parser


def _run_write(templates_dir: Path, out_dir: Path) -> int:
    """Regenerate both artifacts and report what was written."""
    compiled_path, fonts_path = write_artifacts(templates_dir, out_dir)
    print(f"wrote {compiled_path} and {fonts_path} from {templates_dir}")
    return 0


def _run_check(templates_dir: Path, out_dir: Path) -> int:
    """Report drift between a fresh build and the committed artifacts.

    Passes vacuously when the templates do not exist yet, mirroring
    the ``ids_drift`` session's guard.
    """
    if not templates_dir.is_dir() or not _templates_present(templates_dir):
        print(f"{templates_dir} has no templates yet - nothing to check")
        return 0
    diffs = check_artifacts(templates_dir, out_dir)
    if not diffs:
        print(
            f"{out_dir / COMPILED_CSS_NAME} and {out_dir / FONTS_CSS_NAME} match {templates_dir}"
        )
        return 0
    for line in diffs:
        print(f"drift: {line}")
    return 1


def main(argv: Sequence[str] | None = None) -> int:
    """Run the CLI: dispatch to ``--write`` or ``--check``."""
    args = _build_parser().parse_args(argv)
    try:
        if args.write:
            return _run_write(args.templates_dir, args.out_dir)
        return _run_check(args.templates_dir, args.out_dir)
    except (TailwindCliMissingError, TailwindCompileError, OSError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2


# logic-coverage-exempt: T-3 unreachable when loaded by
# spec_from_file_location -- the repo's established test pattern never
# executes this module as __main__, so the guard's True branch is
# never taken under coverage.
if __name__ == "__main__":
    sys.exit(main())
