# SPDX-License-Identifier: GPL-3.0-only
"""Unit tests for tools/gen_htmlexport_goldens.py (E6.2.2).

The generator freezes the two results-page goldens at
``tests/unit/fixtures/htmlexport/epic-2026-results*.html`` plus their
``payload-*.json`` fixtures, regenerated once from the real renderer
with the samples' ``race-data`` JSON as input (TB-5: the hand-assembled
samples' bespoke whitespace is not reproduced; the regenerated bytes
are the contract). Value-parity with the samples' parsed JSON is
checked before anything is written, so a renderer change that would
alter the embedded record fails generation rather than silently
freezing different data.

``tools/`` is a dev-script tree, not an installed package, so the
module under test is loaded from its file path (the pattern
test_gen_css.py:40 established).
"""

import importlib.util
import json
from pathlib import Path
from types import ModuleType  # noqa: TC003 -- used at runtime as a return type here

import pytest
from htmlexport_fixtures import (
    GOLDEN_NO_TIMES,
    GOLDEN_TIMES,
    NO_TIMES_SAMPLE,
    TIMES_SAMPLE,
    parse_race_data,
)

_GEN_GOLDENS_PATH = Path(__file__).resolve().parents[2] / "tools" / "gen_htmlexport_goldens.py"


def _load_gen_goldens(path: Path) -> ModuleType:
    """Load tools/gen_htmlexport_goldens.py by path (not a package)."""
    spec = importlib.util.spec_from_file_location("gen_htmlexport_goldens", path)
    if spec is None or spec.loader is None:
        msg = f"could not build a module spec for {path}"
        raise ImportError(msg)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


gen_goldens = _load_gen_goldens(_GEN_GOLDENS_PATH)

_ROOT = Path(__file__).resolve().parents[2]
_COMMITTED_FIXTURES_DIR = _ROOT / "tests" / "unit" / "fixtures" / "htmlexport"


# ------------------------------------------- the honest regeneration


@pytest.mark.parametrize(
    "name",
    [
        "payload-times.json",
        "epic-2026-results.html",
        "payload-no-times.json",
        "epic-2026-results-no-times.html",
    ],
)
def test_write_goldens_regeneration_matches_committed_file_byte_for_byte(
    name: str, tmp_path: Path
) -> None:
    """Regenerating from the samples reproduces every committed file."""
    gen_goldens.write_goldens(gen_goldens.DEFAULT_SAMPLES_DIR, tmp_path)

    assert (tmp_path / name).read_bytes() == (_COMMITTED_FIXTURES_DIR / name).read_bytes()


def test_regenerated_goldens_hold_value_parity_with_samples() -> None:
    """The frozen goldens' race-data matches the samples' value.

    This is the TB-5 freeze contract: the bytes may differ from the
    hand-assembled samples (loop whitespace), but the embedded record
    must not.
    """
    assert parse_race_data(GOLDEN_TIMES) == parse_race_data(TIMES_SAMPLE)
    assert parse_race_data(GOLDEN_NO_TIMES) == parse_race_data(NO_TIMES_SAMPLE)


def test_regenerated_golden_is_production_self_contained_page() -> None:
    """The frozen golden ships zero fetchable external refs (R-61).

    ``https://`` itself appears only inside the vendored
    ``compiled_css`` license comment (E6.2.1's artifact); nothing the
    page loads comes from the network.
    """
    content = GOLDEN_TIMES.read_text(encoding="utf-8")

    assert "http://" not in content
    assert "url(http" not in content
    assert "<script src=" not in content
    assert "<link" not in content
    assert "@tailwindcss/browser" not in content
    assert content.count("<script") == 1


def test_generated_fixture_json_parses_to_the_sample_record() -> None:
    """payload-*.json is the samples' race-data as a stable file."""
    times_fixture = _COMMITTED_FIXTURES_DIR / "payload-times.json"
    record = json.loads(times_fixture.read_text(encoding="utf-8"))

    assert record == parse_race_data(TIMES_SAMPLE)


# ----------------------------------------------------------- CLI modes


def test_main_write_with_out_dir_override_writes_four_files(tmp_path: Path) -> None:
    """``--write --out-dir`` points the generator at a scratch tree."""
    out_dir = tmp_path / "out"

    exit_code = gen_goldens.main(
        [
            "--write",
            "--out-dir",
            str(out_dir),
            "--samples-dir",
            str(gen_goldens.DEFAULT_SAMPLES_DIR),
        ]
    )

    assert exit_code == 0
    assert (out_dir / "epic-2026-results.html").is_file()
    assert (out_dir / "epic-2026-results-no-times.html").is_file()
    assert (out_dir / "payload-times.json").is_file()
    assert (out_dir / "payload-no-times.json").is_file()


def test_main_write_returns_two_when_sample_missing(tmp_path: Path) -> None:
    """A missing sample is a hard error, never a partial freeze."""
    empty = tmp_path / "empty"
    empty.mkdir()

    exit_code = gen_goldens.main(["--write", "--samples-dir", str(empty)])

    assert exit_code == 2


def test_main_check_returns_zero_when_committed_goldens_match() -> None:
    """``--check`` passes when a fresh regeneration matches."""
    exit_code = gen_goldens.main(["--check"])

    assert exit_code == 0


def test_main_check_returns_one_with_drift_when_golden_modified(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """A stale golden fails the build with a ``drift:`` line."""
    out_dir = tmp_path / "out"
    gen_goldens.main(["--write", "--out-dir", str(out_dir)])
    golden = out_dir / "epic-2026-results.html"
    golden.write_text(golden.read_text(encoding="utf-8") + "\n", encoding="utf-8")

    exit_code = gen_goldens.main(["--check", "--out-dir", str(out_dir)])

    assert exit_code == 1
    assert "drift: epic-2026-results.html" in capsys.readouterr().out
